version: "3.4"

services:
  db:
    image: postgres:14
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  app:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "9857:8000"
    depends_on:
      - db
    links:
      - db

volumes:
    db_data: {}
