[tool.poetry]
name = "desafio-solfacil"
version = "0.1.0"
description = ""
authors = ["Luiz Braga"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.2"
djangorestframework = "^3.14.0"
psycopg2-binary = "^2.9.6"
pre-commit = "^3.2.2"
django-phonenumber-field = {extras = ["phonenumbers"], version = "^7.0.2"}
requests = "^2.28.2"
pandas = "^2.0.0"
drf-yasg = "^1.21.5"
django-environ = "^0.10.0"
gunicorn = "^20.1.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''